[package]
name = "sdu-report-cs"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Dregen_Yor"]
license = "GPL-3.0"
description = "A report template for SDU CS students"
keywords = ["presentation", "report", "experience", "sdu"  ]
categories = ["presentation"]
repository = "https://github.com/Dregen-Yor/sdu-touying-simpl"
compiler = "0.12.0"

[template]
path = "example"
entrypoint = "main.typ"
thumbnail = "example/figures/main.png"